--------------------------------------------------------
--  File created - Saturday-March-03-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADS_COMPANY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADS_COMPANY" 
   (	"COMPANY_CODE" VARCHAR2(50 BYTE), 
	"COMPANY_NAME" VARCHAR2(200 BYTE), 
	"BRANCH_CODE" VARCHAR2(50 BYTE), 
	"BRANCH_NAME" VARCHAR2(200 BYTE), 
	"COLUMN1" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADS_COMPANY_DATA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADS_COMPANY_DATA" 
   (	"COMPANY_CODE" VARCHAR2(50 BYTE), 
	"COMPANY_NAME" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."ADS_COMPANY_DATA"."COMPANY_CODE" IS 'PK_ADS_COMPANY';
--------------------------------------------------------
--  DDL for Table ADS_MEDIA
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADS_MEDIA" 
   (	"MEDIA_CODE" VARCHAR2(50 BYTE), 
	"MEDIA_DESCRIPTION" VARCHAR2(200 BYTE), 
	"PROMATION_NAME" VARCHAR2(200 BYTE), 
	"COMPANY_CODE" VARCHAR2(50 BYTE), 
	"BRANCH_CODE" VARCHAR2(50 BYTE), 
	"POSITION_CODE" VARCHAR2(50 BYTE), 
	"MEDIA_TYPE_CODE" VARCHAR2(50 BYTE), 
	"BRANCH_FLOOR" VARCHAR2(200 BYTE), 
	"ZONE_CODE" VARCHAR2(50 BYTE), 
	"MEDIA_NO" VARCHAR2(50 BYTE), 
	"VENDOR_CODE" VARCHAR2(50 BYTE), 
	"MEDIA_WIDTH" FLOAT(126), 
	"MEDIA_LONG" FLOAT(126), 
	"UNIT_CODE" VARCHAR2(50 BYTE), 
	"MEDIA_IMG" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."ADS_MEDIA"."COMPANY_CODE" IS 'FK_ADS_COMPANY';
   COMMENT ON COLUMN "SYSTEM"."ADS_MEDIA"."BRANCH_CODE" IS 'FK_ADS_COMPANY';
   COMMENT ON COLUMN "SYSTEM"."ADS_MEDIA"."POSITION_CODE" IS 'FK_ADS_POSITION';
   COMMENT ON COLUMN "SYSTEM"."ADS_MEDIA"."MEDIA_TYPE_CODE" IS 'FK_ADS_MEDIA_TYPE';
   COMMENT ON COLUMN "SYSTEM"."ADS_MEDIA"."ZONE_CODE" IS 'FK_ADS_ZONE';
   COMMENT ON COLUMN "SYSTEM"."ADS_MEDIA"."VENDOR_CODE" IS 'FK_ADS_VENDOR';
   COMMENT ON COLUMN "SYSTEM"."ADS_MEDIA"."UNIT_CODE" IS 'FK_ADS_UNIT';
--------------------------------------------------------
--  DDL for Table ADS_MEDIA_PRICE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADS_MEDIA_PRICE" 
   (	"MEDIA_PRICE_CODE" VARCHAR2(50 BYTE), 
	"MEDIA_CODE" VARCHAR2(50 BYTE), 
	"MEDIA_PRICE_COST" FLOAT(126), 
	"MEDIA_PRICE_SALES" FLOAT(126), 
	"MEDIA_PRICE_NET" FLOAT(126), 
	"MEDIA_PERIOD_CODE" VARCHAR2(50 BYTE), 
	"COLUMN1" DATE, 
	"MEDIA_PERIOD_FINISH" DATE, 
	"COLUMN2" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADS_MEDIA_TYPE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADS_MEDIA_TYPE" 
   (	"MEDIA_TYPE_CODE" VARCHAR2(50 BYTE), 
	"MEDIA_TYPE_NAME" VARCHAR2(200 BYTE), 
	"POSITION_CODE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."ADS_MEDIA_TYPE"."POSITION_CODE" IS 'FK_ADS_POSITION';
--------------------------------------------------------
--  DDL for Table ADS_POSITION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADS_POSITION" 
   (	"POSTION_CODE" VARCHAR2(50 BYTE), 
	"POSITION_NAME" VARCHAR2(200 BYTE), 
	"COMPANY_CODE" VARCHAR2(50 BYTE), 
	"BRANCH_CODE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."ADS_POSITION"."COMPANY_CODE" IS 'FK_ADS_COMPANY';
   COMMENT ON COLUMN "SYSTEM"."ADS_POSITION"."BRANCH_CODE" IS 'FK_ADS_COMPANY';
--------------------------------------------------------
--  DDL for Table ADS_TIME_PERIOD
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADS_TIME_PERIOD" 
   (	"TIME_PERIOD_CODE" VARCHAR2(50 BYTE), 
	"TIME_PERIOD_NAME" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADS_UNIT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADS_UNIT" 
   (	"UNIT_CODE" VARCHAR2(50 BYTE), 
	"UNIT_NAME" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADS_VENDOR
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADS_VENDOR" 
   (	"VENDOR_CODE" VARCHAR2(50 BYTE), 
	"VENDOR_NAME" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ADS_ZONE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."ADS_ZONE" 
   (	"ZONE_CODE" VARCHAR2(50 BYTE), 
	"ZONE_NAME" VARCHAR2(200 BYTE), 
	"COMPANY_CODE" VARCHAR2(50 BYTE), 
	"BRANCH_CODE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SYSTEM"."ADS_ZONE"."COMPANY_CODE" IS 'FK_ADS_COMPANY';
   COMMENT ON COLUMN "SYSTEM"."ADS_ZONE"."BRANCH_CODE" IS 'FK_ADS_COMPANY';
REM INSERTING into SYSTEM.ADS_COMPANY
SET DEFINE OFF;
REM INSERTING into SYSTEM.ADS_COMPANY_DATA
SET DEFINE OFF;
REM INSERTING into SYSTEM.ADS_MEDIA
SET DEFINE OFF;
REM INSERTING into SYSTEM.ADS_MEDIA_PRICE
SET DEFINE OFF;
REM INSERTING into SYSTEM.ADS_MEDIA_TYPE
SET DEFINE OFF;
REM INSERTING into SYSTEM.ADS_POSITION
SET DEFINE OFF;
REM INSERTING into SYSTEM.ADS_TIME_PERIOD
SET DEFINE OFF;
REM INSERTING into SYSTEM.ADS_UNIT
SET DEFINE OFF;
REM INSERTING into SYSTEM.ADS_VENDOR
SET DEFINE OFF;
REM INSERTING into SYSTEM.ADS_ZONE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index COMPANY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."COMPANY_PK" ON "SYSTEM"."ADS_COMPANY" ("COMPANY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADS_COMPANY_DATA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ADS_COMPANY_DATA_PK" ON "SYSTEM"."ADS_COMPANY_DATA" ("COMPANY_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADS_MEDIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ADS_MEDIA_PK" ON "SYSTEM"."ADS_MEDIA" ("MEDIA_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADS_MEDIA_PRICE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ADS_MEDIA_PRICE_PK" ON "SYSTEM"."ADS_MEDIA_PRICE" ("MEDIA_PRICE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADS_MEDIA_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ADS_MEDIA_TYPE_PK" ON "SYSTEM"."ADS_MEDIA_TYPE" ("MEDIA_TYPE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADS_POSITION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ADS_POSITION_PK" ON "SYSTEM"."ADS_POSITION" ("POSTION_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADS_TIME_PERIOD_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ADS_TIME_PERIOD_PK" ON "SYSTEM"."ADS_TIME_PERIOD" ("TIME_PERIOD_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADS_UNIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ADS_UNIT_PK" ON "SYSTEM"."ADS_UNIT" ("UNIT_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADS_VENDOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ADS_VENDOR_PK" ON "SYSTEM"."ADS_VENDOR" ("VENDOR_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADS_ZONE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."ADS_ZONE_PK" ON "SYSTEM"."ADS_ZONE" ("ZONE_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table ADS_COMPANY
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADS_COMPANY" ADD CONSTRAINT "COMPANY_PK" PRIMARY KEY ("COMPANY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ADS_COMPANY" MODIFY ("BRANCH_CODE" NOT NULL ENABLE);
  ALTER TABLE "SYSTEM"."ADS_COMPANY" MODIFY ("COMPANY_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADS_COMPANY_DATA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADS_COMPANY_DATA" ADD CONSTRAINT "ADS_COMPANY_DATA_PK" PRIMARY KEY ("COMPANY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ADS_COMPANY_DATA" MODIFY ("COMPANY_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADS_MEDIA
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADS_MEDIA" ADD CONSTRAINT "ADS_MEDIA_PK" PRIMARY KEY ("MEDIA_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ADS_MEDIA" MODIFY ("MEDIA_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADS_MEDIA_PRICE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADS_MEDIA_PRICE" ADD CONSTRAINT "ADS_MEDIA_PRICE_PK" PRIMARY KEY ("MEDIA_PRICE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ADS_MEDIA_PRICE" MODIFY ("MEDIA_PRICE_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADS_MEDIA_TYPE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADS_MEDIA_TYPE" ADD CONSTRAINT "ADS_MEDIA_TYPE_PK" PRIMARY KEY ("MEDIA_TYPE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ADS_MEDIA_TYPE" MODIFY ("MEDIA_TYPE_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADS_POSITION
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADS_POSITION" ADD CONSTRAINT "ADS_POSITION_PK" PRIMARY KEY ("POSTION_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ADS_POSITION" MODIFY ("POSTION_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADS_TIME_PERIOD
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADS_TIME_PERIOD" ADD CONSTRAINT "ADS_TIME_PERIOD_PK" PRIMARY KEY ("TIME_PERIOD_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ADS_TIME_PERIOD" MODIFY ("TIME_PERIOD_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADS_UNIT
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADS_UNIT" ADD CONSTRAINT "ADS_UNIT_PK" PRIMARY KEY ("UNIT_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ADS_UNIT" MODIFY ("UNIT_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADS_VENDOR
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADS_VENDOR" ADD CONSTRAINT "ADS_VENDOR_PK" PRIMARY KEY ("VENDOR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ADS_VENDOR" MODIFY ("VENDOR_CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADS_ZONE
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."ADS_ZONE" ADD CONSTRAINT "ADS_ZONE_PK" PRIMARY KEY ("ZONE_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SYSTEM"."ADS_ZONE" MODIFY ("ZONE_CODE" NOT NULL ENABLE);
